ONEM-27757: other warnings and issues (#7)
compilation warnings removed
.gitignore updated

Second compilation failed on builds with gssdp-1.0
Adressed warnings:
/home/mikolaj.staworzynski/projects/eos2008c_20220922/onemw/onemw-src/onemw-xdialserver/server/plat/rtcache.cpp:47:95: warning: format '%s' expects argument of type 'char*', but argument 2 has type 'std::__cxx11::string* {aka std::__cxx11::basic_string<char>*}' [-Wformat=]
/home/mikolaj.staworzynski/projects/eos2008c_20220922/onemw/onemw-src/onemw-xdialserver/server/plat/rtcache.cpp:52:95: warning: format '%s' expects argument of type 'char*', but argument 2 has type 'std::__cxx11::string* {aka std::__cxx11::basic_string<char>*}' [-Wformat=]
/home/mikolaj.staworzynski/projects/eos2008c_20220922/onemw/onemw-src/onemw-xdialserver/server/gdial-ssdp.c:162:3: warning: format not a string literal, argument types not checked [-Wformat-nonliteral]
/home/mikolaj.staworzynski/projects/eos2008c_20220922/onemw/onemw-src/onemw-xdialserver/server/gdial-ssdp.c:163:3: warning: format not a string literal, argument types not checked [-Wformat-nonliteral]
/home/mikolaj.staworzynski/projects/eos2008c_20220922/onemw/onemw-src/onemw-xdialserver/server/main.c:197:3: warning: implicit declaration of function 'gdial_plat_register_friendlyname_cb' [-Wimplicit-function-declaration]
/home/mikolaj.staworzynski/projects/eos2008c_20220922/onemw/onemw-src/onemw-xdialserver/server/main.c:199:3: warning: not enough variable arguments to fit a sentinel [-Wformat=]
/home/mikolaj.staworzynski/projects/eos2008c_20220922/onemw/onemw-src/onemw-xdialserver/server/main.c:200:3: warning: not enough variable arguments to fit a sentinel [-Wformat=]
/home/mikolaj.staworzynski/projects/eos2008c_20220922/onemw/onemw-src/onemw-xdialserver/server/main.c:201:3: warning: not enough variable arguments to fit a sentinel [-Wformat=]
/home/mikolaj.staworzynski/projects/eos2008c_20220922/onemw/onemw-src/onemw-xdialserver/server/main.c:262:13: warning: passing argument 1 of 'free' discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]

TODO: check - Conflicts:
   server/main.c